 [ui.anchors]
bottom = true
left = true
right = true
top = true

[ui.window]
h_align = "fill"
v_align = "fill"

  [ui.window.box]
  h_align = "center"
 # v_align = "center"
  width = 450

    [ui.window.box.ai_scroll]
    h_align = "fill"
    height = 500
    max_height = 500
    min_width = 400
    name = "aiScroll"
    v_align = "fill"
    width = 400

      [ui.window.box.ai_scroll.list]
      name = "aiList"
      orientation = "vertical"
      spacing = 10
      width = 400

        [ui.window.box.ai_scroll.list.item]
        h_align = "fill"
        name = "aiItem"
        v_align = "fill"
        wrap = true
        x_align = 0
        y_align = 0

      [ui.window.box.ai_scroll.margins]
      top = 8

    [ui.window.box.bar]
    orientation = "horizontal"
    position = "end"

      [ui.window.box.bar.entry]
      h_align = "fill"
      h_expand = true

        [ui.window.box.bar.entry.icon]
        h_align = "center"
        h_expand = true
        pixel_size = 24
        theme = ""

[ui.window.box.scroll.list]
max_height = 495
max_width = 500
min_width = 600
width = 400
height = 120
marker_color = "#FFFFFF"

[ui.window.box.scroll.list.item.activation_label]
hide = true
h_align = "fill"
v_align = "fill"
width = 20
x_align = 0.5
y_align = 0.5

[ui.window.box.scroll.list.item.icon]
pixel_size = 26
theme = ""

  [ui.window.box.scroll.list.margins]
  top = 8

[ui.window.box.search.clear]
h_align = "center"
icon = "edit-clear"
name = "clear"
pixel_size = 18
theme = ""
v_align = "center"

[ui.window.box.search.input]
h_align = "fill"
h_expand = true
icons = true

[ui.window.box.search.prompt]
h_align = "center"
icon = "edit-find"
name = "prompt"
pixel_size = 18
theme = ""
v_align = "center"

[ui.window.box.search.spinner]
hide = true
