
[config]
reload_apps = true

[config.wallpaper]
command = "swww"
arguments = [
    "img", "-t", "outer",
    "--transition-duration", "1.5",
    "--transition-step", "255",
    "--transition-fps", "60",
    "-f", "Nearest"
]
set = true

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.hyprland]
input_path = "~/.config/Ax-Shell/config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/matugen/config/hypr/colors.conf"

[templates.ax-shell]
input_path = "~/.config/Ax-Shell/config/matugen/templates/ax-shell.css"
output_path = "~/.config/matugen/styles/colors.css"
post_hook = "fabric-cli exec ax-shell 'app.set_css()' &; python3 ~/.config/Ax-Shell/vesktop_preprocessor.py &"

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/niri/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'
