complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "switch" -d "Build and switch to this configuration"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "boot" -d "Build and add to boot loader menu"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "test" -d "Build and switch to this configuration but don't add to boot menu"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "build" -d "Build but don't switch to this configuration"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "edit" -d "Open the configuration in $EDITOR"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "repl" -d "Open a Nix REPL with the configuration"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "dry-build" -d "Show what would be built"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "dry-run" -d "Show what would be built (alias for dry-build)"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "dry-activate" -d "Show what would be activated"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "build-image" -d "Build a NixOS image"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "build-vm" -d "Build a virtual machine"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "build-vm-with-bootloader" -d "Build a virtual machine with bootloader"
complete -c nixos-rebuild -n "__fish_use_subcommand" -x -a "list-generations" -d "List all generations"

# Options
complete -c nixos-rebuild -s v -l verbose -d "Verbose output"
complete -c nixos-rebuild -l quiet -d "Quiet output"
complete -c nixos-rebuild -s j -l max-jobs -x -d "Maximum number of parallel jobs"
complete -c nixos-rebuild -l cores -x -d "Number of CPU cores to use"
complete -c nixos-rebuild -l log-format -x -d "Log format"
complete -c nixos-rebuild -s k -l keep-going -d "Keep going after failed builds"
complete -c nixos-rebuild -s K -l keep-failed -d "Keep temporary directories of failed builds"
complete -c nixos-rebuild -l fallback -d "Fall back to building from source if substitution fails"
complete -c nixos-rebuild -l repair -d "Repair corrupted store paths"
complete -c nixos-rebuild -l option -x -d "Set a Nix configuration option"
complete -c nixos-rebuild -l builders -x -d "Remote builders to use"
complete -c nixos-rebuild -s I -l include -x -d "Add a path to the Nix search path"
complete -c nixos-rebuild -s L -l print-build-logs -d "Print build logs as they happen"
complete -c nixos-rebuild -l show-trace -d "Show a stack trace for evaluation errors"
complete -c nixos-rebuild -l accept-flake-config -d "Accept flake configuration"
complete -c nixos-rebuild -l refresh -d "Consider all previously downloaded files out of date"
complete -c nixos-rebuild -l impure -d "Allow impure expressions"
complete -c nixos-rebuild -l offline -d "Disable substituters and only use local store"
complete -c nixos-rebuild -l no-net -d "Disable network access"
complete -c nixos-rebuild -l recreate-lock-file -d "Recreate the flake lock file"
complete -c nixos-rebuild -l no-update-lock-file -d "Don't update the flake lock file"
complete -c nixos-rebuild -l no-write-lock-file -d "Don't write the flake lock file"
complete -c nixos-rebuild -l no-registries -d "Don't use flake registries"
complete -c nixos-rebuild -l commit-lock-file -d "Commit changes to the flake lock file"
complete -c nixos-rebuild -l update-input -x -d "Update a specific flake input"
complete -c nixos-rebuild -l override-input -x -d "Override a specific flake input"
complete -c nixos-rebuild -s Q -l no-build-output -d "Don't show build output"
complete -c nixos-rebuild -l use-substitutes -d "Use substitutes if available"
complete -c nixos-rebuild -s s -l substitute-on-destination -d "Use substitutes on destination"
complete -c nixos-rebuild -s h -l help -d "Show help"
complete -c nixos-rebuild -l debug -d "Show debug output"
complete -c nixos-rebuild -s f -l file -r -d "NixOS configuration file"
complete -c nixos-rebuild -s A -l attr -x -d "Attribute to build"
complete -c nixos-rebuild -l flake -x -d "Flake URL"
complete -c nixos-rebuild -l no-flake -d "Don't use flakes"
complete -c nixos-rebuild -l install-bootloader -d "Install bootloader"
complete -c nixos-rebuild -l install-grub -d "Install GRUB bootloader"
complete -c nixos-rebuild -s p -l profile-name -x -d "Profile name"
complete -c nixos-rebuild -s c -l specialisation -x -d "Specialisation to build"
complete -c nixos-rebuild -l rollback -d "Roll back to previous configuration"
complete -c nixos-rebuild -l upgrade -d "Upgrade NixOS"
complete -c nixos-rebuild -l upgrade-all -d "Upgrade all packages"
complete -c nixos-rebuild -l json -d "Output in JSON format"
complete -c nixos-rebuild -l ask-sudo-password -d "Ask for sudo password"
complete -c nixos-rebuild -l sudo -d "Use sudo"
complete -c nixos-rebuild -l use-remote-sudo -d "Use remote sudo"
complete -c nixos-rebuild -l no-ssh-tty -d "Don't allocate a TTY for SSH"
complete -c nixos-rebuild -l no-reexec -d "Don't re-exec nixos-rebuild"
complete -c nixos-rebuild -l fast -d "Skip steps that aren't essential"
complete -c nixos-rebuild -l build-host -x -d "Remote build host"
complete -c nixos-rebuild -l target-host -x -d "Remote target host"
complete -c nixos-rebuild -l no-build-nix -d "Don't build Nix"
complete -c nixos-rebuild -l image-variant -x -d "Image variant to build"
