# ~/.config/starship.toml

format = """
$hostname\
$directory\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$hg_branch\
$docker_context\
$package\
$custom\
$sudo\
$fill\
$git_branch\
$git_status\
$git_commit\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$line_break\
$character"""

add_newline = true

# ========================
# BLOCK-STYLE MODULES
# ========================

# ~/.config/starship.toml

[hostname]
format = "[ $ssh_symbol$hostname ](bold bg:#24273a fg:#E8E3E3)"  # Added spaces inside brackets
disabled = false

[directory]
format = "[ $path ]($style)[   ](bg:#8caaee fg:#24273a)"  # Double spaces around folder icon
style = "bg:#24273a fg:#E8E3E3 bold"

[cmd_duration]
format = "[ $duration ]($style)[ 󱑂  ](bg:#ca9ee6 fg:#24273a)"  # Padded clock icon

[character]
success_symbol = "[ •   ](#8caaee bold)"  # Added spaces between symbols
error_symbol = "[ •  󰅙 ](#e78284 bold)"

[git_branch]
format = "[ $branch ]($style) [  ](bg:#81C19B fg:#24273a)"  # Added space between branch and icon
style = "bg:#24273a fg:#E8E3E3"
symbol = " "

[git_status]
format = "[ $all_status$ahead_behind ]($style) [  ](bg:#8caaee fg:#24273a)"  # Added space between status and icon
style = "bg:#24273a fg:#E8E3E3"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"

[battery]
format = "[ $symbol$percentage ](bold fg:#a6e3a1)"  # Added internal spacing
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
display = [
    { threshold = 10, style = "bold fg:#e78284" },  # Red when critical
    { threshold = 30, style = "bold fg:#ef9f76" },  # Orange when low
    { threshold = 100, style = "bold fg:#a6e3a1" }  # Green otherwise
]
# ========================
# DISABLED LANGUAGE MODULES
# ========================
[aws]
format = "[$symbol]($style)"
symbol = " "
style = "bold yellow"

[python]
format = "[$symbol]($style)"
symbol = " "
style = "bold yellow"

[nodejs]
format = "[$symbol]($style)"
symbol = " "
style = "bold green"

# Disable unused language modules
c.disabled = true
cmake.disabled = true
haskell.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
java.disabled = true
golang.disabled = true
